# Generated by Django 4.0.4 on 2022-05-04 06:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(help_text='Write your answer here...', max_length=2000)),
                ('date_created', models.DateField(default=datetime.datetime(2022, 5, 4, 6, 49, 18, 670118, tzinfo=utc), null=True)),
                ('date_updated', models.DateField(default=datetime.datetime(2022, 5, 4, 6, 49, 18, 670118, tzinfo=utc), null=True)),
                ('upvote', models.IntegerField(default=0)),
                ('downvote', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('date_created', models.DateField(default=datetime.datetime(2022, 5, 4, 6, 49, 18, 670118, tzinfo=utc), null=True)),
                ('credits', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Enter your question in brief', max_length=1000)),
                ('date_created', models.DateField(default=datetime.datetime(2022, 5, 4, 6, 49, 18, 670118, tzinfo=utc), null=True)),
                ('date_updated', models.DateField(default=datetime.datetime(2022, 5, 4, 6, 49, 18, 670118, tzinfo=utc), null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myquora.author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(help_text='Enter your comment...', max_length=1000)),
                ('date_created', models.DateField(default=datetime.datetime(2022, 5, 4, 6, 49, 18, 670118, tzinfo=utc))),
                ('date_updated', models.DateField(default=datetime.datetime(2022, 5, 4, 6, 49, 18, 670118, tzinfo=utc))),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myquora.answer')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myquora.author')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myquora.author'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myquora.question'),
        ),
    ]
